name: Run E2E tests on schedule
on:
  schedule:
    # run every monday (will run on the default branch, so here main)
    - cron:  '0 0 * * 1'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run e2e tests
        run: ./gradlew check

      - name: Upload Test Results on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path:  build/reports/tests/test
