name: Run E2E tests on schedule
on:
  schedule:
    # run every monday (will run on the default branch, so here main)
    - cron:  '0 0 * * 1'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/gradlew
        id: gradlew
        with:
          publish: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path:  build/reports/tests/test
