name: Run tests & publish doc
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore(main): release')
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/gradlew
        id: gradlew
        with:
          publish: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.gradlew.outputs.jar_file }}

      - name: Generate Documentation
        if: success()
        run: ./gradlew dokkaHtml

      - name: Deploy to Github Pages 🚀
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build/dokka/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
