name: Run tests & publish doc
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path:  build/reports/tests/test
          retention-days: 30

      - name: Generate Jar
        if: success()
        run: ./gradlew jar

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          path:  build/libs/*.jar

      - name: Generate Documentation
        if: success()
        run: ./gradlew dokkaHtml

      - name: Deploy to Github Pages 🚀
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/dokka/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
