name: Run tests
on:
  push:
    branches-ignore:
      - main
      - gh-pages
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew check

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path:  build/reports/tests/test
          retention-days: 30