name: Run tests
on:
  push:
    branches-ignore:
      - main
      - gh-pages
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/gradlew
        id: gradlew
        with:
          run_checks: 'true'
          publish: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
